### PR TITLE
Add nav native

### PR DESCRIPTION
**Pull request by boldtrn**
This PR updates the mapbox-navigation-ui dependency to the latest version. This version contains the closed source nav native library. 

While the current version adds a lot of benefits and fixes a lot of issues I have seen a couple of new issues as well. There are cases where `simulate route` stops working and the position is not updated anymore, I recommend to use [Lockito](https://play.google.com/store/apps/details?id=fr.dvilleneuve.lockito) for testing instead. I have also seen cases where my GPS position hasn't been updated in a real life test and I needed to restart the app. These findings need further testing though.

BTW: With mapbox-android-navigation-ui:0.22.0` there is a new way of requesting the location from the SDK, that's why there are changes with the `locationLayer`. My findings above could be connected to this and might be fixed in the next version.
BTW2: there are some minor side changes that I don't think require a separate PR, if you think differently, let me know, then I will split them up into separate PRs.

### CODE REVIEW

**Comment by karussell** [comment]
Thanks!

> I have also seen cases where my GPS position hasn't been updated in a real life test and I needed to restart the app

I have seen this with an older version as well.

**Comment by boldtrn** [comment]
> I have seen this with an older version as well.

Thanks for letting me know, then this might be unrelated, just wanted to report it :).

**Comment by devemux86** [comment]
> This version contains the closed source nav native library.

Their navigation library is not fully open source?

**Comment by karussell** [comment]
> Their navigation library is not fully open source?

Well, they currently mess around with license issues in their open source repository, yes. See (and upvote) here: https://github.com/mapbox/mapbox-navigation-android/issues/1391

**Comment by boldtrn** [comment]
I will close this PR due to the licensing issues with Mapbox Native.

**Pull request closed without merging**
