### PR TITLE
Add geocoding

### LINKED ISSUE #11: Investigate GPS issues
Sometimes there seems to be an issue with finding the GPS position, while other apps find the GPS position. We should have a look and see what could be done about this or if we can reproduce it.

### PR DESCRIPTION
**Pull request by boldtrn**
This PR adds geocoding and closes #11.

So far the geocoding is still very basic, no autocomplete, no selectable provider, etc.

However, the basics work, you can choose the language, the search results are influenced by the current map position (by passing point).

### CODE REVIEW

**Comment by boldtrn** [comment]
I updated the PR.

We now zoom automatically after performing the geocoding so that the current location and the results are shown on one screen. Note: there is one issue with this, if you are for example in Germany and are searching for "New York" you will end up somewhere in the middle because you cannot zoom out that much, we could remove the current location, but it's still possible that there are issues, for example when you search for "Greenwich" or for "Simpson" you get results from the UK, USA, and Australia, so the map cannot zoom to all results at once. For most searches, especially in the surrounding area this shouldn't be an issue and the current approach works quite nice IMHO. However, it's easily changeable.

Also if you long press on the info window, the point will be included in the route.

**Comment by karussell** [comment]
This works good already - thanks!

Two minor things:

1. 

> Also if you long press on the info window, the point will be included in the route.

Is it possible to use a normal press instead of long press?

2. is it possible to keep the last search :) ?

**Comment by boldtrn** [comment]
> Is it possible to use a normal press instead of long press?

Yes this would be possible. I would not recommend this though. A regular tap happens easily by accident, and we don't have a "revert/undo" function, so it might become annoying quite quickly.

 > is it possible to keep the last search :) ?

This is the same issue as #14. I think this has to be possible somehow, but I wasn't able to get it done the last time (I didn't try too long, I guess with a bit more research I would be able to come up with a solution or as an alternative create own activities instead of Dialogs, which could solve this).

**Comment by karussell** [comment]
> A regular tap happens easily by accident, and we don't have a "revert/undo" function, so it might become annoying quite quickly.

Did you tried it and was it annoying? As the markers stays on the map a re-routing is relative fast (?)

> I think this has to be possible somehow

Could it work with [this](https://stackoverflow.com/a/26475582/194609) and input.setText (or grabbing the textView from the dialog)

**Comment by boldtrn** [comment]
> Did you tried it and was it annoying? As the markers stays on the map a re-routing is relative fast (?)

The thing is, right now, the point is appended to the route, which allows to plan routes, from Munich, via Stuttgart, to Berlin. So one would have to clear the whole route to undo this (also on route clear, we currently clear the geocoding results).

That's why I thought a long press makes more sense, to avoid adding a point by accident.

I can change this if you like?

> Could it work with this and input.setText (or grabbing the textView from the dialog)

Thanks for pointing me in that direction, this seems to work! I just committed this :) (including the tap on the info-window).

**Comment by karussell** [comment]
Great - thanks!

> I can change this if you like?

For a geocoding highly likely only one destination is chosen so I would prefer having this option simple via single click.

**Comment by boldtrn** [comment]
> For a geocoding highly likely only one destination is chosen so I would prefer having this option simple via single click.

Ok, no problem. It is currently committed like this, with a simple tap.

**Comment by karussell** [comment]
Thanks - good to merge for me!

**Review by karussell — APPROVED** [review]

**Comment by boldtrn** [comment]
Thanks, merged :)

**Pull request merged**
